name: MathWorks
description: "Конструктор математических задач с поддержкой различных тем и уровней сложности"

# Версионирование в формате MAJOR.MINOR.PATCH+BUILD
version: 1+1.0.0

# Минимальные требования к SDK
environment:
  sdk: ^3.7.0

# Зависимости приложения
dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.3
  open_file: ^3.3.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  window_manager: ^0.3.9
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Конфигурация Flutter
flutter:
  fonts:
    - family: Times
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/timesbd.ttf
          weight: 700
        - asset: assets/fonts/timesi.ttf
          style: italic
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Italic.ttf

# Метаданные приложения
authors:
  - JollyRoll <kirill45189rik@gmail.com>
homepage: https://github.com/JollyRollXx/MathWorks_Constructor
repository: https://github.com/JollyRollXx/MathWorks_Constructor
documentation: https://github.com/JollyRollXx/MathWorks_Constructor/wiki

# Настройки сборки
build:
  windows:
    target-platform: windows-x64
