name: first_flutter_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.3
  open_file: ^3.3.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  window_manager: ^0.3.9
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Times
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/timesbd.ttf
          weight: 700
        - asset: assets/fonts/timesi.ttf
          style: italic
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Italic.ttf
